export const ADD_ANNOTATION = 'ADD_ANNOTATION';
export const UPDATE_ANNOTATION = 'UPDATE_ANNOTATION';
export const MOVE_ANNOTATION_TO_FRONT = 'MOVE_ANNOTATION_TO_FRONT';
export const REMOVE_ANNOTATION = 'REMOVE_ANNOTATION';
export const SET_SELECTED_SPEAKER = 'SET_SELECTED_SPEAKER';
export const SET_SPEAKER_COLOR = 'SET_SPEAKER_COLOR';
export const SET_CURRENT_SCENE = 'SET_CURRENT_SCENE';
export const SET_CURRENT_CAMERA = 'SET_CURRENT_CAMERA';